### PR TITLE
Use named import/exports where possible

### LINKED ISSUE #22: Use named imports/exports
In the recent versions of ECMAScript, the `default` import and exports should be avoided as they can cause several problems and a lot of confusion for beginners.  I think this project should use named exports/imports instead.

### PR DESCRIPTION
**Pull request by aminya**
Fixes #22

### CODE REVIEW

**Review by aminya — COMMENTED** [review]
Unfortunately, the `lazy` function expects a `Promise<{ default: Component }>`. So, using named import with lazy is kind of clunky. We should probably fix that and change the remaining components in another pull request. In my opinion, it should also accept `Promise<Component>`

**Comment by amoutonbrady** [comment]
Yes... The other issue is that HMR might break if we don't have default exported components.
I think the latest version might have fixed the issue but I need to confirm that.

**Comment by JLarky** [comment]
> Unfortunately, the `lazy` function expects a `Promise<{ default: Component }>`. So, using named import with lazy is kind of clunky. We should probably fix that and change the remaining components in another pull request. In my opinion, it should also accept `Promise<Component>`

<strike>I wonder if it's possible to create something like https://www.npmjs.com/package/react-lazily but for solid :) it should probably work without any changes :)</strike>

I just tested and react-lazily could be easily ported to solidjs :) see this example:
https://codesandbox.io/s/solidjs-using-react-lazily-244e3?file=/src/App.js:282-831

```js
// before
const Nav = lazy(() => import("./components/Nav"));
// after
const { Nav } = lazily(() => import("./components/Nav"));
```

**Comment by amoutonbrady** [comment]
Oh that's really cool! I'd have to see how well it plays with HMR first :)

**Comment by JLarky** [comment]
> Oh that's really cool! I'd have to see how well it plays with HMR first :)

I don't imagine there could be any difference :)

**Comment by amoutonbrady** [comment]
I think this issue has run its course. The solution proposed to make named exports work are quite cool but I don't think they should belong in a starter template.

We should probably find a way to expose this solution though :)

**Pull request closed without merging**
