### PR TITLE
=>windi.config.ts

### PR DESCRIPTION
**Pull request by dharmaturtle**
Technically `tailwind.config.[jt]s` [works](https://windicss.org/guide/configuration.html#config-file)... but the templates use windi. So renaming for consistency.

### CODE REVIEW

**Comment by russelgal** [comment]
and... a webstorm is out )

**Comment by dharmaturtle** [comment]
That discussion indicates that its a workaround - not an officially supported feature:

> It doesn't provide full support though

> using tailwind.config.js hack does not seems to be working any more

IMO a SolidJS template should not use a windicss hack. If a template's dependency doesn't have great support for a certain editor, that's on the dependency, not Solid.

**Comment by amoutonbrady** [comment]
I'm starting to question the windicss choice. Sure it's a rather popular option for vite based user but outside of it... I don't know. I'll have to consider.

In the meantime, I think I'll add a tailwind starter and see where we go from here.

**Comment by millette** [comment]
FYI, I used https://github.com/antfu/unocss#vite and https://github.com/antfu/unocss/tree/main/packages/preset-wind and https://www.npmjs.com/package/@unocss/reset (@unocss/reset/tailwind.css) instead of windi and it worked perfectly.

**Pull request closed without merging**
